checks:
  php: true

filter:
  paths:
    - src/*

build:
  image: default-bionic

  environment:
    variables:
      YII_ENV: test

    php:
      version: 8.0.21
      ini:
        xdebug.mode: coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    codeception:
      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: vendor/bin/codecept run --coverage-xml
            on_node: 1
            coverage:
              file: runtime/tests/_output/coverage.xml
              format: php-clover
